[APPAI-1461] Go Lang Support for SA and CA
fabric8-analytics/fabric8-analytics-vscode-extension pull request #407
Opened 2020-08-31 12:56 UTC by dgpatelgit

Added support for GO ecosystem:

https://issues.redhat.com/browse/APPAI-1461

2020-09-02 07:23 UTC, arajkumar reviewed
Can we refactor the code to follow "Open-close" principle? The existing one is too invasive and needs modification in quite a bit of places in the form of `if..else` which is against "Open-close" principle.

My proposal is to come up with an interface and each ecosystem can implement the interface to generate the dependency graph?

Something like below,

```
interface IDependencyGraphGenerator {
    async resolvedGraph(manifestPath: uri): uri;
}

// for each ecosystem
// pypi.ts
class PyPi implements IDependencyGraphGenerator {
    async resolvedGraph(manifestPath: uri): uri {
        ..
        return exec(command)
    }
}

// golang.ts
class Golang implements IDependencyGraphGenerator {
}
...
```

2020-09-02 07:50 UTC, dgpatelgit commented
> Can we refactor the code to follow "Open-close" principle? The existing one is too invasive and needs modification in quite a bit of places in the form of `if..else` which is against "Open-close" principle.
> 
> My proposal is to come up with an interface and each ecosystem can implement the interface to generate the dependency graph?
> 
> Something like below,
> 
> ```
> interface IDependencyGraphGenerator {
>     async resolvedGraph(manifestPath: uri): uri;
> }
> 
> // for each ecosystem
> // pypi.ts
> class PyPi implements IDependencyGraphGenerator {
>     async resolvedGraph(manifestPath: uri): uri {
>         ..
>         return exec(command)
>     }
> }
> 
> // golang.ts
> class Golang implements IDependencyGraphGenerator {
> }
> ...
> ```

This pattern is really good to handle the problem we have with various ecosystem. But taking time constraint we have this sprint, can we create a separate story for code refactoring / cleanup, where we can clean up all ecosystem code as well.

2020-09-02 10:14 UTC, arajkumar commented
@dgpatelgit It won't take a lot of time to refactor., because the logic is going to remain same. I prefer to do it now rather later.

2020-09-04 08:25 UTC, arajkumar reviewed
Overall changes looks ok to me. Could you please add a test to cover newly added code?

2020-09-04 08:25 UTC, arajkumar commented on src/Utils.ts
> +  }
Isn't vscode settings `go.goPath` referes to [GOPATH](https://golang.org/doc/gopath_code.html#GOPATH) which holds all go modules & build artifacts?

2020-09-09 10:02 UTC, dgpatelgit commented
For refactoring activity, new story https://issues.redhat.com/browse/APPAI-1477 is created.

2020-09-15 07:31 UTC, arajkumar commented
[test]

2020-09-15 07:40 UTC, arajkumar requested changes
Overall changes looks good to me.

@dgpatelgit Could you please update README.md.

2020-09-23 11:15 UTC, arajkumar approved these changes
lgtm

2020-09-23 11:16 UTC, arajkumar commented
[test]

2020-09-23 11:57 UTC, dgpatelgit commented
> [test]

I have added test for generating gograph.txt manifest. Rest of the flow is common as other ecosystem. 
Do you see any specific test to be added?

2020-09-23 12:02 UTC, mathur07 approved these changes

2020-09-23 12:33 UTC, merged