chore: Update README.md for release version 0.2.0
fabric8-analytics/fabric8-analytics-vscode-extension pull request #417
Opened 2020-10-01 14:54 UTC by dvandra

2020-10-05 15:27 UTC, prashbnair requested changes

2020-10-05 15:27 UTC, prashbnair commented on README.md
> +1. By clicking on the `Sign up for a free Snyk account` from 'Dependency Analytics report' goes to the Snyk sign up page for a free Snyk account. Just after signing up for a free Snyk account it goes
```suggestion
1. Clicking on the `Sign up for a free Snyk account` from 'Dependency Analytics report' will take you to the Snyk sign up page for a free Snyk account. After signing up for a free Snyk account it goes to the 'Snyk's Landing page' which shows `Snyk token` to connect Snyk with your Red Hat Dependency Analytics. Copy and paste the Snyk token into Red Hat Dependency Analytics Report as shows below.
```

2020-10-05 15:27 UTC, prashbnair commented on README.md
> +3. After successfully entering the Snyk token the Dependency Analyitcs report will updated with the detailed information of security vulnerability unique to snyk and vulnerabilities having publicly k
```suggestion
3. After successfully entering the Snyk token the Dependency Analyitcs report will be updated with detailed information about security vulnerabilities unique to Snyk and vulnerabilities having publicly known exploits.
```

2020-10-06 01:56 UTC, prashbnair commented on README.md
> +1. Clicking on the `Sign up for a free Snyk account` from 'Dependency Analytics report' will take you to the Snyk sign up page for a free Snyk account. After signing up for a free Snyk account it goe
```suggestion
1. Clicking on the `Sign up for a free Snyk account` from 'Dependency Analytics report' will take you to the Snyk sign up page for a free Snyk account. After signing up for a free Snyk account it goes to the 'Snyk's Landing page' which shows `Snyk token` to connect Snyk with your Red Hat Dependency Analytics. Copy and paste the Snyk token into Red Hat Dependency Analytics Report as shown below.
```

2020-10-06 01:56 UTC, prashbnair approved these changes

2020-10-06 07:33 UTC, mathur07 approved these changes

2020-10-06 07:38 UTC, mathur07 commented
@dvandra are we updating the CA gif with new shortcut icon or it fine?

2020-10-06 07:54 UTC, dvandra commented
> @dvandra are we updating the CA gif with new shortcut icon or its fine?

@mathur07 I have just updated the gif with new shortcut icon.
PTAL

2020-10-06 08:00 UTC, mathur07 approved these changes
LGTM

2020-10-06 08:00 UTC, arajkumar requested changes
@dvandra Some of the screenshots has to be updated with latest "Button text" #423

2020-10-06 08:28 UTC, arajkumar approved these changes
lgtm

2020-10-06 08:28 UTC, merged