fix: Update CHANGELOG for release version 0.3.0-beta
fabric8-analytics/fabric8-analytics-vscode-extension pull request #463
Opened 2020-12-09 12:56 UTC by dgpatelgit

2020-12-09 13:34 UTC, arajkumar requested changes

2020-12-09 13:34 UTC, arajkumar commented on CHANGELOG.md
> +## 0.3.0-beta (December 9th, 2020)
```suggestion
## 0.3.0(December 9th, 2020)
```

2020-12-09 13:34 UTC, arajkumar commented on CHANGELOG.md
> +- fixes - Question: Are there plans to support Golang? See [#436](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/436)
```suggestion
```

2020-12-10 04:59 UTC, arajkumar approved these changes
lgtm

2020-12-10 05:00 UTC, dvandra approved these changes
LGTM

2020-12-10 05:00 UTC, merged