chore: Update README.md for release version 0.3.0
fabric8-analytics/fabric8-analytics-vscode-extension pull request #475
Opened 2020-12-24 11:16 UTC by dvandra

Updating GIFs and Screenshots with latest UI Changes.

2020-12-24 13:11 UTC, arajkumar requested changes
@dvandra , Please include the changelog  & version updates in the same PR.

2021-01-04 03:30 UTC, dvandra commented
> @dvandra , Please include the changelog & version updates in the same PR.

On it!

2021-01-04 05:18 UTC, dgpatelgit approved these changes
lgtm

2021-01-04 06:00 UTC, arajkumar requested changes

2021-01-04 06:00 UTC, arajkumar commented on CHANGELOG.md
> +    - Use concise text for CA popup. See [#472](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/472)
Concise text is not part of lsp.

```suggestion
    - Use concise text for CA popup. See [#472](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/472)
```

2021-01-04 06:00 UTC, arajkumar commented on CHANGELOG.md
>      - Golang CA support from LSP. See [#148](https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/148)
Add the following under lsp,

https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/176
https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/177
https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/172

2021-01-04 07:11 UTC, arajkumar approved these changes
lgtm

2021-01-04 07:13 UTC, merged